//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakıp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personelızınlerı
    {
        public int ID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string IzınTuru { get; set; }
        public Nullable<System.DateTime> GıdısTarih { get; set; }
        public Nullable<System.DateTime> DonusTarih { get; set; }
        public Nullable<int> AlınanIzınSayısı { get; set; }
        public Nullable<int> KalanIzınSayısı { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> Sicil { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
