//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakıp.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Personelızınlerı = new HashSet<Personelızınlerı>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DaıreID { get; set; }
        public Nullable<int> BırımID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Sicil { get; set; }
        public string Tel_1 { get; set; }
        public string Tc { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> IsActıve { get; set; }
        public Nullable<int> ızın { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public Nullable<System.DateTime> DonusTarih { get; set; }
    
        public virtual Birimler Birimler { get; set; }
        public virtual DaıreBas DaıreBas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personelızınlerı> Personelızınlerı { get; set; }
    }
}
